Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

In [2]:
def gen_vander_matrix(input_vector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    
    return op_matx

In [5]:
input_vector = np.array([1,2,3,4,5])
no_col = 3
dec_order = gen_vander_matrix(input_vector,no_col,False)
inc_order = gen_vander_matrix(input_vector,no_col,True)
print(dec_order)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


In [6]:
print(inc_order)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


# Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

Note: Solution submitted via github must contain all the detailed steps.



In [29]:
def mov_avg(input_vect,window_size):
    for i in range(0,(input_vect.size-window_size+1)):
        sum=0
        j=0
        #print("i=",i)
        while j<window_size:
            
            sum=sum+input_vect[j+i]
            j=j+1
            
            #print(j)
        print("average of ",i+1,"th window is ",(sum/window_size))
    

In [30]:
input_vect=np.array([10,20,30,40,50,60,70,80,90,100])
window_size=4
mov_avg(input_vect,window_size)

average of  1 th window is  25.0
average of  2 th window is  35.0
average of  3 th window is  45.0
average of  4 th window is  55.0
average of  5 th window is  65.0
average of  6 th window is  75.0
average of  7 th window is  85.0


In [31]:
input_vect=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window_size=3
mov_avg(input_vect,window_size)

average of  1 th window is  5.0
average of  2 th window is  4.666666666666667
average of  3 th window is  5.666666666666667
average of  4 th window is  6.666666666666667
average of  5 th window is  9.666666666666666
average of  6 th window is  28.666666666666668
average of  7 th window is  49.333333333333336
average of  8 th window is  72.66666666666667
average of  9 th window is  84.0
average of  10 th window is  93.33333333333333
average of  11 th window is  116.33333333333333
