Task 1:
1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
try:
    num1=int(input("enter the numerator"))
    num2=int(input("enter the denominator"))
    div=num1/num2
    print("the division of 2 numbers is: ",div)
except:
    print("Divide by zero exception caught")

enter the numerator10
enter the denominator0
Divide by zero exception caught


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [3]:
subject=["Americans","Indians"]
verb=["Play","watch"]
Object=["Baseball","cricket"]
for i in subject:
    for j in verb:
        for k in Object:
            print("{} {} {}.".format(i,j,k))

Americans Play Baseball.
Americans Play cricket.
Americans watch Baseball.
Americans watch cricket.
Indians Play Baseball.
Indians Play cricket.
Indians watch Baseball.
Indians watch cricket.


Task 2:
1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde

In [9]:
import numpy as np
def vander(iterable,power):
    print(np.vander(iterable,power,increasing=True))
iterable=[1,2,3,4,5]
power=3
vander(iterable,power)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
